### ISSUE TITLE
Final domain name?

### ISSUE THREAD

**Issue by SeanKilleen** [excellalabs/labs-website#24]
Will this be labs.excella.com? or ExcellaLabs.com? We haven't thought about wiring up the DNS yet.

**Comment by 5arias** [comment]
excella.io and excellalabs.com are the two that have been currently approved. 

They need to be pointed to the production S3 bucket:
http://excellalabs.s3-website-us-east-1.amazonaws.com/

**Comment by SeanKilleen** [comment]
@5arias doesn't the production S3 bucket need to have the same name as the domain name?

**Comment by SeanKilleen** [comment]
http://docs.aws.amazon.com/AmazonS3/latest/dev/website-hosting-custom-domain-walkthrough.html

**Comment by 5arias** [comment]
@SeanKilleen as a matter of fact, we do need to do that. Thank you for the reminder!

@duluca once you confirm with Fadi as to which domain name will be the primary, I can setup the proper buckets and update deployment to them in TravisCI

**Comment by duluca** [comment]
@Wyntuition please point both ExcellLabs.com and Excella.io to the ECS container setup with #59

**Comment by duluca** [comment]
done
